import '../language_screen/widgets/listchineses_item_widget.dart';import '../language_screen/widgets/listenglishuk_item_widget.dart';import 'package:flutter/material.dart';import 'package:mohammed_s_application1/core/app_export.dart';import 'package:mohammed_s_application1/widgets/app_bar/appbar_image.dart';import 'package:mohammed_s_application1/widgets/app_bar/appbar_title.dart';import 'package:mohammed_s_application1/widgets/app_bar/custom_app_bar.dart';class LanguageScreen extends StatelessWidget {const LanguageScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA70001, appBar: CustomAppBar(height: getVerticalSize(51), leadingWidth: getHorizontalSize(48), leading: AppbarImage(svgPath: ImageConstant.imgGroup162799, margin: getMargin(left: 24, top: 13, bottom: 14), onTap: () {onTapArrowbackone(context);}), centerTitle: true, title: AppbarTitle(text: "Language")), body: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 28, right: 24, bottom: 28), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: getPadding(left: 16, top: 21, right: 16, bottom: 21), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: getPadding(top: 2), child: Text("Suggested Languages", style: CustomTextStyles.labelLargeSemiBold)), Expanded(child: Padding(padding: getPadding(top: 16), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: getPadding(top: 7.0, bottom: 7.0), child: SizedBox(width: getHorizontalSize(295), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.indigo50)));}, itemCount: 3, itemBuilder: (context, index) {return ListenglishukItemWidget();})))])))), Expanded(child: SizedBox(width: double.maxFinite, child: Container(margin: getMargin(top: 24, bottom: 5), padding: getPadding(all: 16), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: getPadding(top: 3), child: Text("Other Languages", style: CustomTextStyles.labelLargeSemiBold)), Expanded(child: Padding(padding: getPadding(top: 19), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: getPadding(top: 8.0, bottom: 8.0), child: SizedBox(width: getHorizontalSize(295), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.indigo50)));}, itemCount: 6, itemBuilder: (context, index) {return ListchinesesItemWidget();})))]))))])))); } 


/// Navigates back to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is used
/// to navigate back to the previous screen.
onTapArrowbackone(BuildContext context) { Navigator.pop(context); } 
 }
